export const FETCH_ALL_POST_REQUEST = "FETCH_ALL_POST_REQUEST";
export const FETCH_ALL_POST_SUCCESS = "FETCH_ALL_POST_SUCCESS";
export const FETCH_ALL_POST_FAIL = "FETCH_ALL_POST_FAIL";

export const USER_NEWPOST_REQUEST = "USER_NEWPOST_REQUEST";
export const USER_NEWPOST_SUCCESS = "USER_NEWPOST_SUCCESS";
export const USER_NEWPOST_FAIL = "USER_NEWPOST_FAIL";
