export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_RSUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const MSG_WITH_USER_REQUEST = "MSG_WITH_USER_REQUEST";
export const MSG_WITH_USER_SUCCESS = "MSG_WITH_USER_RSUCCESS";
export const MSG_WITH_USER_FAIL = "MSG_WITH_USER_FAIL";

export const USER_MESSAGES_REQUEST = "USER_MESSAGES_REQUEST";
export const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
export const USER_MESSAGES_FAIL = "USER_MESSAGES_FAIL";

export const CLEAR_MSG_WINDOW_R = "CLEAR_MSG_WINDOW_R";
export const CLEAR_MSG_WINDOW_S = "CLEAR_MSG_WINDOW_S";