export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_RSUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const USER_MESSAGES_REQUEST = "USER_MESSAGES_REQUEST";
export const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
export const USER_MESSAGES_FAIL = "USER_MESSAGES_FAIL";

export const CLEAR_MSG_WINDOW_R = "CLEAR_MSG_WINDOW_R";
export const CLEAR_MSG_WINDOW_S = "CLEAR_MSG_WINDOW_S";

export const GET_CHAT_USER_REQ = "GET_CHAT_USER_REQ";
export const GET_CHAT_USER_SUC = "GET_CHAT_USER_SUC";
export const GET_CHAT_USER_FAIL = "GET_CHAT_USER_FAIL";
