export const GET_OTHER_USER_REQUEST = "GET_OTHER_USER_REQUEST";
export const GET_OTHER_USER_SUCCESS = "GET_OTHER_USER_SUCCESS";
export const GET_OTHER_USER_FAIL = "GET_OTHER_USER_FAIL";

export const GET_ALL_USERS_REQ = "GET_ALL_USERS_REQ";
export const GET_ALL_USERS_SUC = "GET_ALL_USERS_SUC";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
